### PR TITLE
Junior developer has created Test 2

### PR DESCRIPTION
**Pull request by test080791**
Hi Lead,

I have commited Test 2.
Please review & approve.

Regards,
Junior Developer

### CODE REVIEW

**Comment by test080791** [comment]
Hi Lead,

I have created another method in class Test2.
Please review

Regards,
Junior Developer

**Review by ApurvaBarot — CHANGES_REQUESTED** [review]
Please keep same name with TestA & Test B

**Comment by test080791** [comment]
I have given naming convention as per your suggestion.

**Review by ApurvaBarot — APPROVED** [review]
Code accepted

**Pull request merged**
